### ISSUE TITLE
BrowserSync Not updating

### ISSUE THREAD

**Issue by natewalsh** [johndavemanuel/bootstrap4-gulp-starter-template#11]
I am having trouble getting my BrowserSync to reload after I make a change. Any suggestions?

**Comment by ymarescaux** [comment]
> I am having trouble getting my BrowserSync to reload after I make a change. Any suggestions?

Replace like this : 

`watch('src/**/*.html').on('change', series(resetPages, compileHTML, browserSync.reload));`

It work for me...

**Comment by johndavemanuel** [comment]
What file changes you are getting trouble? I try HTML and it is working fine

**Comment by codenpixel** [comment]
Same issue here.I'm having trouble getting BS to reload css chages?
Update: BS stop reloading page when some error come up

**Comment by johndavemanuel** [comment]
Hi @ShareBootstrap 

I push a new update for watch files

**Comment by codenpixel** [comment]
Hi @johndavemanuel
That was fast.   :) 
Maybe it's something on my side but it looks like it doesn't work,some new issue popup

**Comment by johndavemanuel** [comment]
May i see the error on your command line or may I know what is the new issue?

**Comment by natewalsh** [comment]
I added the on change event that Sangohan62 suggested and everything is working fine now. Thanks for checking.

**Comment by johndavemanuel** [comment]
@natewalsh great

@ShareBootstrap 
Just let me know if any error happen on your end
