### ISSUE TITLE
Problem with "gulp prod" and vendor file

### ISSUE THREAD

**Issue by tommix95** [johndavemanuel/bootstrap4-gulp-starter-template#17]
When I launch "gulp prod" and publish the project I no longer see the font-awesome5 that I have used within the project.
With "gulp dev" they are seen correctly. Is there a problem in the gulpfile with the production and the vendor folder? or is not it to you?

P.S
This is the best bootstrap starter!

**Comment by johndavemanuel** [comment]
Hello there! I just using GitHub mobile , did you add that manually?

**Comment by tommix95** [comment]
In the vendor/css folder there was already font-awesome5

and the <head> results in the call
<link rel = "stylesheet" href = "{{root}} assets / vendor / css / font-awesome5.css">

I put the fonts in the html via <i class = ""> </i> tag

only that as soon as I launch "prod" they are not seen, with "dev", instead everything works.

**Comment by johndavemanuel** [comment]
I see. let me check and get back to you

**Comment by johndavemanuel** [comment]
I make an update to fix the issue, I am thinking also to integrate font awesome 5 PRO but not sure if it is allow on the license to use it.

**Comment by tommix95** [comment]
I don't think the pro version is allowed.

you removed the folder:
src/assets/vendor/css/

but in layout there is this:

<link rel="stylesheet" href="{{root}}assets/vendor/css/font-awesome5.css">

**Comment by tommix95** [comment]
<link rel="stylesheet" href="{{root}}assets/vendor/css/linea-arrows-styles.css">

**Comment by tommix95** [comment]
I don't think the pro version is allowed.

you removed the folder:
src/assets/vendor/css/

but in layout there is this:
build:css 
{{root}}assets/vendor/css/font-awesome5.css
