### ISSUE TITLE
Problem with "gulp prod" and files in "pages" subfolder

### ISSUE THREAD

**Issue by tommix95** [johndavemanuel/bootstrap4-gulp-starter-template#18]
I give an example:

If I create a new folder "blog" and a new file "single.html" in "pages" assigning it the basic layout "default.html".

With the "gulp prod" command, any javascript inserted in custom.js has no effect on "single.html", it doesn't seem to load any script as it still expects to find them in the "vendor" folder even in production.

Hope it helps :)

**Comment by johndavemanuel** [comment]
Hi!

Is this issue related to this PR? #19

**Comment by tommix95** [comment]
yes, I solved it that way.

**Comment by johndavemanuel** [comment]
I will check the PR and merge it :)
