### ISSUE TITLE
kleur do not define a valid './colors'

### ISSUE THREAD

**Issue by dembee111** [johndavemanuel/bootstrap4-gulp-starter-template#26]
while kleur do not define a valid './colors'        is it ansi-colors ?

**Comment by johndavemanuel** [comment]
Hello @dembee111, sorry I did not get what you mean? Can you ellaborate?

**Comment by dembee111** [comment]
So sorry, This error occurred while gulp dev command  ( kleur do not define a valid './colors )

**Comment by johndavemanuel** [comment]
I see. let me check

**Comment by dembee111** [comment]
There is an error from the lower version of npm or nodejs. Thank you
