### ISSUE TITLE
gulp dev/gulp prod

### ISSUE THREAD

**Issue by spwebguy** [johndavemanuel/bootstrap4-gulp-starter-template#27]
Hello,

I don't know if _README_ isn't updated or I'm missing something but I had to run `gulp development` and `gulp production` instead of what's described in the _README_ file. 

Just letting you know.

**Comment by johndavemanuel** [comment]
Hi @spwebguy 

I forgot to update the readme. Thanks for letting me know

**Comment by johndavemanuel** [comment]
I already change the readmore

**Comment by spwebguy** [comment]
Cool thanks!
